# Generated by Django 4.1.3 on 2023-02-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubname', models.CharField(max_length=50, unique=True)),
                ('clubimage', models.FileField(default='club/none/no-img.jpg', upload_to='club/')),
                ('clubamount', models.CharField(max_length=25)),
                ('clubmembers', models.CharField(max_length=25)),
                ('clubcontribution', models.CharField(max_length=20)),
                ('startdate', models.DateField(null=True)),
                ('starttime', models.TimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IssueMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('mobileno', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('motive', models.CharField(max_length=100)),
                ('income', models.CharField(max_length=50)),
                ('monthlycontribution', models.CharField(max_length=50)),
                ('profileimg', models.ImageField(blank=True, null=True, upload_to='user/')),
                ('email', models.CharField(max_length=50)),
                ('alternateno', models.CharField(blank=True, max_length=50)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='userkyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('aadharno', models.CharField(max_length=50, unique=True)),
                ('aadharfrontimg', models.FileField(blank=True, default='aadhar/none/no-img.jpg', upload_to='aadhar/')),
                ('aadharbackimg', models.FileField(blank=True, default='aadhar/none/no-img.jpg', upload_to='aadhar/')),
                ('panno', models.CharField(max_length=50, unique=True)),
                ('panimg', models.FileField(blank=True, default='pan/none/no-img.jpg', upload_to='pan/')),
                ('is_verified', models.BooleanField(default=False)),
                ('registeruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundno', models.CharField(max_length=20, null=True)),
                ('roundname', models.CharField(max_length=20, null=True)),
                ('minbid', models.CharField(max_length=20, null=True)),
                ('maxbid', models.CharField(max_length=20, null=True)),
                ('winner', models.CharField(max_length=20, null=True)),
                ('roundamount', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('is_completed', models.BooleanField(null=True)),
                ('clubname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.club')),
            ],
        ),
        migrations.CreateModel(
            name='invite_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_join', models.BooleanField(default=False)),
                ('clubname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nameclub', to='api.club')),
                ('inviteto', models.ManyToManyField(to='api.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=500, null=True)),
                ('status', models.BooleanField(default=False)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='api.issuemessages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='api.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='bankdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerno', models.CharField(max_length=25, unique=True)),
                ('IFSCcode', models.CharField(max_length=25)),
                ('accountname', models.CharField(max_length=25)),
                ('accountnumber', models.CharField(max_length=25, unique=True)),
                ('passbookimg', models.FileField(blank=True, default='passbook/none/no-img.jpg', upload_to='passbook/')),
                ('registeruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_registration')),
            ],
        ),
    ]
