# Generated by Django 4.1.3 on 2023-02-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_rounds_clubname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='duration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
