# Generated by Django 4.1.3 on 2023-02-22 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rounds_duration_rounds_startdate_rounds_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite_user',
            name='inviteto',
        ),
        migrations.AddField(
            model_name='invite_user',
            name='inviteto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviteuser', to='api.user_registration'),
        ),
    ]
