# Generated by Django 4.1.3 on 2023-02-24 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_invite_user_inviteto_invite_user_inviteto'),
    ]

    operations = [
        migrations.CreateModel(
            name='cashwallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletamount', models.CharField(blank=True, max_length=30)),
                ('totalamount', models.CharField(blank=True, max_length=50)),
                ('walletimg', models.FileField(blank=True, default='passbook/none/no-img.jpg', upload_to='passbook/')),
                ('walletwithdraw', models.CharField(blank=True, max_length=30)),
                ('casdate', models.DateTimeField(auto_now=True)),
                ('is_added', models.BooleanField(default=False)),
                ('is_withdraw', models.BooleanField(default=False)),
                ('userwallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=30)),
                ('biduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_registration')),
                ('roundbid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rounds')),
            ],
        ),
    ]
