# Generated by Django 4.1.3 on 2023-02-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cashwallet_casdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='wallet_amount',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
