# Generated by Django 4.1.3 on 2023-02-28 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_registration_wallet_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletamount', models.CharField(max_length=30)),
                ('walletimg', models.FileField(blank=True, default='passbook/none/no-img.jpg', upload_to='passbook/')),
                ('payment_status', models.BooleanField(default=False)),
                ('userwallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_registration')),
            ],
        ),
    ]
