# Generated by Django 4.1.3 on 2023-02-28 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_addmoney'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawamount', models.CharField(max_length=30)),
                ('payment_status', models.BooleanField(default=False)),
                ('userwallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_registration')),
            ],
        ),
    ]
