# Generated by Django 4.1.3 on 2023-02-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rounds_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmoney',
            name='add_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='withdrawmoney',
            name='withdraw_date',
            field=models.DateField(auto_now=True),
        ),
    ]
