# Generated by Django 4.1.3 on 2023-03-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_addmoney_add_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetClubByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.club')),
                ('clubuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_registration')),
            ],
        ),
    ]
