# Generated by Django 4.1.3 on 2023-03-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_club_getclubbyuser_clubid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='token',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
