# Generated by Django 4.1.3 on 2023-03-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_registration_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashwallet',
            name='is_withdraw',
        ),
        migrations.RemoveField(
            model_name='cashwallet',
            name='totalamount',
        ),
        migrations.RemoveField(
            model_name='cashwallet',
            name='walletwithdraw',
        ),
        migrations.AlterField(
            model_name='invite_user',
            name='clubname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nameclub', to='api.club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite_user',
            name='inviteto',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='inviteuser', to='api.user_registration'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Withdrawcashwallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletamount', models.CharField(blank=True, max_length=30)),
                ('walletwithdraw', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('is_withdraw', models.BooleanField(default=False)),
                ('userwallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_registration')),
            ],
        ),
    ]
