# Generated by Django 4.1.3 on 2023-03-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_amounttrasfertime_avgtrasfertime_clubclosedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.CharField(max_length=300)),
                ('data', models.CharField(max_length=500)),
                ('image', models.FileField(blank=True, default='notification/none/no-img.jpg', upload_to='notification/')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
