# Generated by Django 4.1.3 on 2023-03-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_appnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='body',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='data',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='image',
            field=models.FileField(blank=True, default='notification/none/no-img.jpg', null=True, upload_to='notification/'),
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
