# Generated by Django 4.1.3 on 2023-03-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_appnotification_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='usernotification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user_registration'),
            preserve_default=False,
        ),
    ]
