# Generated by Django 4.1.3 on 2023-03-11 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_appnotification_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payamount', models.CharField(max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_time', models.CharField(max_length=50, null=True)),
                ('looser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loose', to='api.user_registration')),
                ('roundpayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rounds')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win', to='api.user_registration')),
            ],
        ),
    ]
