# Generated by Django 4.1.4 on 2023-01-12 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_alter_createpost_date_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='body',
            field=models.TextField(default='3:29', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 15, 29, 48, 309608)),
        ),
    ]
