# Generated by Django 4.1.4 on 2023-01-13 12:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supplier', '0006_alter_createpost_date_followerscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 17, 48, 45, 365130)),
        ),
        migrations.RemoveField(
            model_name='followerscount',
            name='follower',
        ),
        migrations.AlterField(
            model_name='followerscount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followerscount',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='Supplier.followerscount'),
        ),
    ]
