# Generated by Django 4.1.4 on 2023-01-14 07:36

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supplier', '0011_alter_createpost_date_remove_followerscount_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 14, 13, 6, 6, 386508)),
        ),
        migrations.RemoveField(
            model_name='followerscount',
            name='follower',
        ),
        migrations.AddField(
            model_name='followerscount',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
