# Generated by Django 4.1.4 on 2023-01-14 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0013_alter_createpost_date_remove_followerscount_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 14, 15, 34, 58, 948232)),
        ),
        migrations.AlterField(
            model_name='followerscount',
            name='user',
            field=models.CharField(default='3:35', max_length=1000),
            preserve_default=False,
        ),
    ]
