# Generated by Django 4.1.4 on 2023-01-17 06:15

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supplier', '0015_alter_createpost_date_insightfulpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='insightful',
            field=models.ManyToManyField(blank=True, default=None, related_name='insight', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 11, 45, 50, 104350)),
        ),
    ]
