# Generated by Django 4.1.4 on 2023-01-18 06:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supplier', '0023_alter_commentforpost_date_alter_createpost_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerscount',
            name='follower',
        ),
        migrations.AddField(
            model_name='followerscount',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Supplier.createpost'),
        ),
        migrations.AddField(
            model_name='followerscount',
            name='value',
            field=models.CharField(choices=[('Follow', 'Follow'), ('Unfollow', 'Unfollow')], default='Follow', max_length=10),
        ),
        migrations.AlterField(
            model_name='commentforpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 11, 51, 26, 367933)),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 11, 51, 26, 362937)),
        ),
        migrations.AlterField(
            model_name='followerscount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
