# Generated by Django 4.1.4 on 2023-01-18 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0026_remove_createpost_follower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='following_user_id',
            new_name='following',
        ),
        migrations.RenameField(
            model_name='followerscount',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='commentforpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 12, 52, 27, 405778)),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 12, 52, 27, 400782)),
        ),
    ]
