# Generated by Django 4.1.4 on 2023-01-18 07:29

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supplier', '0027_rename_following_user_id_followerscount_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentforpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 12, 59, 56, 692366)),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 12, 59, 56, 688370)),
        ),
        migrations.RemoveField(
            model_name='followerscount',
            name='user',
        ),
        migrations.AddField(
            model_name='followerscount',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
