# Generated by Django 4.1.4 on 2023-01-18 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0031_alter_commentforpost_date_alter_createpost_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerscount',
            name='following',
        ),
        migrations.AddField(
            model_name='followerscount',
            name='follower',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='commentforpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 14, 16, 40, 694651)),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 14, 16, 40, 685660)),
        ),
    ]
