# Generated by Django 4.1.4 on 2023-01-20 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0037_alter_commentforpost_date_alter_createpost_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentforpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 20, 11, 45, 11, 898640)),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 20, 11, 45, 11, 880655)),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
